# grim
# Autogenerated from man page /usr/share/man/man1/grim.1.gz
complete -c grim -s h --description '.'
complete -c grim -s s --description '.'
complete -c grim -s g --description '.'
complete -c grim -s t --description '.'
complete -c grim -s q --description '.'
complete -c grim -s o --description '.'
complete -c grim -s c --description '.'

