# swaybg
# Autogenerated from man page /usr/share/man/man1/swaybg.1.gz
complete -c swaybg -s c -l color --description '.'
complete -c swaybg -s h -l help --description '.'
complete -c swaybg -s i -l image --description '.'
complete -c swaybg -s m -l mode --description '.'
complete -c swaybg -s o -l output --description '.'
complete -c swaybg -s v -l version --description '.'

