# swaymsg
# Autogenerated from man page /usr/share/man/man1/swaymsg.1.gz
complete -c swaymsg -s h -l help --description '.'
complete -c swaymsg -s m -l monitor --description '.'
complete -c swaymsg -s p -l pretty --description '.'
complete -c swaymsg -s q -l quiet --description '.'
complete -c swaymsg -s r -l raw --description '.'
complete -c swaymsg -s s -l socket --description '.'
complete -c swaymsg -s t -l type --description '.'
complete -c swaymsg -s v -l version --description '.'

