# swayidle
# Autogenerated from man page /usr/share/man/man1/swayidle.1.gz
complete -c swayidle -s h --description '.'
complete -c swayidle -s d --description '.'
complete -c swayidle -s w --description '.'

